import { IProject } from "@/types/global";

export const projects: IProject[] = [
  {
    id: 1,
    name: "Jendela Jatim",
    description:
      "A website showcasing several famous tourist destinations in East Java, Indonesia",
    longDesc:
      "Jendela Jatim is an interactive tourism website that highlights some of the most iconic destinations across East Java, Indonesia. Featuring stunning visuals and detailed descriptions, it serves as a gateway for travelers looking to explore the rich cultural and natural heritage of the region.",
    features: [
      "Tourist attraction display",
      "Brief description of the attraction",
      "Photos of various tourist attractions with filter features",
    ],
    images: [
      "/projects/jendela-jatim/1.png",
      "/projects/jendela-jatim/2.png",
      "/projects/jendela-jatim/3.png",
    ],
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    role: "Frontend",
    year: "Oct 2024",
    link: "https://d4yezz.github.io/Jendela-Jatim/",
    repo: "https://github.com/D4yezz/Jendela-Jatim",
  },
  {
    id: 2,
    name: "BankSampah K8",
    description:
      "A website to help manage waste data at SMKN 8 Malang vocational school while providing economic benefits.",
    longDesc:
      "BankSampah K8 is a waste management platform built for SMKN 8 Malang vocational school. It streamlines the collection, tracking, and reporting of recyclable waste data while incentivizing students and staff through economic benefits, promoting a greener school environment.",
    features: [
      "List of waste items and their prices",
      "Form for recording and calculating waste prices",
      "Proof of total waste price via receipt",
      "Automatic messages with criticism and suggestions sent to a spreadsheet",
    ],
    images: [
      "/projects/bank-sampah/1.png",
      "/projects/bank-sampah/2.png",
      "/projects/bank-sampah/3.png",
      "/projects/bank-sampah/4.png",
      "/projects/bank-sampah/5.png",
    ],
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    role: "Frontend",
    year: "Nov 2024",
    link: "https://d4yezz.github.io/BankSampah-K8-24/",
    repo: "https://github.com/D4yezz/BankSampah-K8-24",
  },
  {
    id: 3,
    name: "Explore Ngalam",
    description:
      "A website to discover the natural beauty and diversity of tourism in Malang, East Java, Indonesia.",
    longDesc:
      "Explore Ngalam invites visitors to uncover the breathtaking landscapes and cultural diversity of Malang and its surrounding areas. Built as a fullstack application with React and Supabase, it offers dynamic content management and a seamless browsing experience for travelers.",
    features: [
      "Structured data management with full CRUD functionality for destinations, facilities, and ticketing systems.",
      "Relational database design ensuring seamless integration between destinations, facilities, and ticket data.",
      "Image upload support for enriching destination content with visual representations.",
      "Dynamic display of all tourism destinations with optimized data rendering.",
      "Advanced data handling with pagination and search functionality for efficient content discovery.",
      "Backend powered by Supabase for scalable and real-time database management.",
      "Modern, responsive, and user-friendly UI/UX design focused on enhancing user exploration experience.",
    ],
    images: [
      "/projects/explore-ngalam/1.png",
      "/projects/explore-ngalam/2.png",
      "/projects/explore-ngalam/3.png",
    ],
    tags: ["React", "TailwindCSS", "shadcn/ui", "JavaScript", "Supabase"],
    role: "Fullstack",
    year: "Oct 2025",
    link: "https://explore-ngalam.vercel.app/",
    repo: "https://github.com/D4yezz/explore-ngalam",
  },
  {
    id: 4,
    name: "Go Rent",
    description:
      "The website provides the best car rental services with the latest cars and guaranteed professional comfort.",
    longDesc:
      "Go Rent is a modern car rental platform offering a curated selection of the latest vehicles with a focus on comfort and professionalism. Featuring smooth animations with Framer Motion and a powerful Supabase backend, it delivers a premium user experience from booking to confirmation.",
    features: [
      "Multi-role access control system (Admin, Staff, and Customer) with clearly separated permissions and workflows.",
      "Secure authentication system with user registration and login functionality.",
      "Real-time dashboard overview displaying rental statistics, vehicle availability, and total registered users.",
      "Full CRUD operations for rentals, vehicles, and user management.",
      "Customer rental history tracking for transparent and personalized user experience.",
      "Comprehensive rental transaction reports with integrated print-ready invoice generation.",
      "Modern, responsive, and user-centered UI/UX design for seamless interaction across devices.",
    ],

    images: [
      "/projects/go-rent/1.png",
      "/projects/go-rent/2.png",
      "/projects/go-rent/3.png",
      "/projects/go-rent/4.png",
      "/projects/go-rent/5.png",
      "/projects/go-rent/6.png",
    ],
    tags: [
      "Next.js",
      "TailwindCSS",
      "JavaScript",
      "shadcn/ui",
      "Framer Motion",
      "Supabase",
    ],
    role: "Fullstack",
    year: "Nov 2025",
    link: "https://go-rent-wine.vercel.app/",
    repo: "https://github.com/D4yezz/Go-Rent",
    accDemo: [
      {
        name: "Demo Staff",
        email: "demopgs@mail.com",
        pass: "demopetugas",
      },
      {
        name: "Demo Admin",
        email: "demoadm@mail.com",
        pass: "demoadmin",
      },
    ],
  },
  {
    id: 5,
    name: "Pentol Ngetop",
    description:
      "Trusted spicy meatball ordering website. With an admin dashboard system to manage orders from buyers.",
    longDesc:
      "Pentol Ngetop is a fullstack food ordering platform specializing in spicy meatballs. It features a customer-facing ordering interface along with a comprehensive admin dashboard for managing orders, inventory, and buyer interactions — all built with modern web technologies.",

    features: [
      "High-conversion Landing Page featuring an intuitive and modern UI/UX design",
      "Secure User Authentication system with distinct Admin and Customer roles",
      "Interactive Admin Dashboard with data visualization for real-time sales monitoring",
      "Robust Management System for seamless product inventory and order handling",
      "Geospatial Integration using Google Maps API for precise delivery address selection",
      "Personalized Customer Portal for tracking order history and transaction status",
    ],

    images: [
      "/projects/pentol-ngetop/5.png",
      "/projects/pentol-ngetop/1.png",
      "/projects/pentol-ngetop/2.png",
      "/projects/pentol-ngetop/3.png",
      "/projects/pentol-ngetop/4.png",
      "/projects/pentol-ngetop/6.png",
      "/projects/pentol-ngetop/7.png",
      "/projects/pentol-ngetop/8.png",
      "/projects/pentol-ngetop/9.png",
    ],
    tags: [
      "Next.js",
      "TailwindCSS",
      "JavaScript",
      "shadcn/ui",
      "Framer Motion",
      "Supabase",
    ],
    role: "Fullstack",
    year: "Dec 2025",
    link: "https://pentol-ngetop.vercel.app/",
    repo: "https://github.com/D4yezz/pentol-ngetop",
    accDemo: [
      {
        name: "Admin Dummy",
        email: "admindummy@mail.com",
        pass: "admindummy1234",
      },
      {
        name: "User Dummy",
        email: "user@mail.com",
        pass: "user1234",
      },
    ],
  },
  {
    id: 6,
    name: "Dayezzz.",
    description:
      "A website to describe myself as a developer and showcase my projects.",
    longDesc:
      "Dayezzz is my personal portfolio website, designed to showcase my journey as a developer. With cinematic scroll effects, smooth Framer Motion animations, and a carefully curated monochrome aesthetic, it serves as a living testament to my skills and creative vision.",
    features: [
      "High-conversion Landing Page featuring an intuitive and modern UI/UX design",
      "Cinematic Scroll Effects with smooth and engaging animations powered by Framer Motion",
      "Dynamic Project Showcase with interactive elements and detailed project descriptions",
      "Personalized About Section highlighting my journey, skills, and aspirations as a developer",
      "Responsive Design ensuring optimal viewing experience across all devices",
    ],
    images: [
      "/projects/dayezzz/1.png",
      "/projects/dayezzz/2.png",
      "/projects/dayezzz/3.png",
      "/projects/dayezzz/4.png",
      "/projects/dayezzz/5.png",
      "/projects/dayezzz/6.png",
      "/projects/dayezzz/7.png",
      "/projects/dayezzz/8.png",
    ],
    tags: [
      "Next.js",
      "TailwindCSS",
      "TypeScript",
      "Zustand",
      "Aceternity",
      "Framer Motion",
      "Lenis",
    ],
    role: "Fullstack",
    year: "Jan 2026",
    link: "https://dayezzz.vercel.app/",
    repo: "https://github.com/D4yezz/dayezzz",
  },
  {
    id: 7,
    name: "AI Sales Page Generator",
    description:
      "An AI-powered web application that transforms raw product or service information into structured, high-converting sales landing pages.",
    longDesc:
      "AI Sales Page Generator is a dynamic SaaS platform designed to streamline marketing copywriting and web layout generation. By leveraging the Gemini AI API, the application processes raw input—such as product descriptions, pricing, and target audiences—and instantly transforms them into beautifully styled, conversion-focused sales pages. Built with a robust full-stack architecture, it features seamless user authentication, secure database persistence, and an interactive live preview engine.",
    features: [
      "Secure User Authentication providing seamless registration, login, and session persistence powered by Supabase",
      "Structured Product Input Form designed to intuitively capture product names, descriptions, target audiences, and unique selling points",
      "Intelligent AI Page Generation using the Gemini API to craft compelling headlines, benefit breakdowns, and persuasive calls-to-action rendered as a styled layout",
      "Interactive Live Preview Component that immediately renders the AI-generated copy into a functional, production-ready landing page design",
      "Personalized Saved Pages Dashboard with full CRUD capabilities, allowing users to safely store, view, re-generate, and delete past sales pages",
    ],
    images: [
      "/projects/ai-sales-generator/3.png",
      "/projects/ai-sales-generator/1.png",
      "/projects/ai-sales-generator/2.png",
      "/projects/ai-sales-generator/4.png",
      "/projects/ai-sales-generator/5.png",
      "/projects/ai-sales-generator/6.png",
    ],
    tags: [
      "Next.js",
      "React",
      "JavaScript",
      "Supabase",
      "Gemini API",
      "shadcn/ui",
      "TailwindCSS",
    ],
    role: "Fullstack",
    year: "Apr 2026",
    link: "https://page-generator-ai.vercel.app/",
    repo: "https://github.com/D4yezz/sales-page-generator",
    accDemo: [
      {
        name: "User Dummy",
        email: "dummy@mail.com",
        pass: "dummy1234",
      },
    ],
  },
  {
    id: 8,
    name: "GlowBotani",
    description:
      "A modern, high-performance web platform for a premium organic skincare brand to showcase natural beauty products and drive sales conversion.",
    longDesc:
      "GlowBotani is a full-featured web application built for an organic skincare MSME (UMKM). Designed with an elegant, natural aesthetic using Next.js App Router and Framer Motion, the platform features a complete multi-page architecture, a dynamic SEO-optimized blog to boost organic reach, an interactive product catalog, integrated Google Maps location services, and direct WhatsApp order triggers tailored to convert visitors into customers.",
    features: [
      "Comprehensive Multi-Page Architecture featuring dedicated sections for Home, About Us, Product Catalog, SEO Blog, and Contact",
      "Dynamic SEO-Optimized Blog System engineered to publish natural skincare articles and improve search engine rankings",
      "Interactive Product Catalog & Advantage Gallery showcasing premium herbal ingredients and specific product benefits",
      "Integrated Store Location via Google Maps along with strategically placed multi-CTA triggers pointing directly to WhatsApp",
      "Maximum Speed & Performance Optimization tuned to deliver top-tier Google PageSpeed scores and seamless mobile UX",
    ],
    images: [
      "/projects/glow-botani/1.png",
      "/projects/glow-botani/2.png",
      "/projects/glow-botani/3.png",
      "/projects/glow-botani/4.png",
      "/projects/glow-botani/5.png",
      "/projects/glow-botani/6.png",
      "/projects/glow-botani/7.png",
      "/projects/glow-botani/8.png",
    ],
    tags: ["Next.js", "TailwindCSS", "Framer Motion", "TypeScript"],
    role: "Frontend Developer",
    year: "July 2026",
    link: "https://glow-botani.vercel.app/",
    repo: "https://github.com/D4yezz/glow-botani",
  },
  {
    id: 9,
    name: "NusaBuild Studio",
    description:
      "A modern, high-performance corporate web platform for a premier architecture and construction studio to showcase structural portfolio and drive client consultations.",
    longDesc:
      "NusaBuild Studio is a full-featured corporate web application engineered for an architecture and construction firm. Built with Next.js App Router, TypeScript, and Framer Motion, the platform features a multi-language architecture (Indonesian & English), interactive portfolio showcases, structured project workflow visualizers, career opportunity listings, an integrated industry news/blog section, and seamless WhatsApp consultation triggers tailored to convert corporate leads into business inquiries.",
    features: [
      "Multilingual Support (i18n) featuring seamless locale switching between Indonesian and English ",
      "Comprehensive Corporate Architecture with dedicated sections for Home, About Us, Services, Projects, Careers, Blog, and Contact ",
      "Interactive Project Portfolio & Detail Pages highlighting structural specifications, client metadata, and architectural showcases ",
      "Strategic Consultation Workflows featuring direct WhatsApp CTA triggers, interactive contact forms, and office location integration ",
      "High-Performance Architecture optimized with Next.js, Tailwind CSS, Framer Motion, and dual Light/Dark mode themes ",
    ],
    images: [
      "/projects/nusa-build/1.png",
      "/projects/nusa-build/2.png",
      "/projects/nusa-build/3.png",
      "/projects/nusa-build/4.png",
      "/projects/nusa-build/5.png",
      "/projects/nusa-build/6.png",
      "/projects/nusa-build/7.png",
      "/projects/nusa-build/8.png",
    ],
    tags: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "next-intl",
    ],
    role: "Frontend Developer",
    year: "August 2026",
    link: "https://nusa-build.vercel.app/",
    repo: "https://github.com/D4yezz/nusa-build",
  },
];
