export const projects = [
  {
    id: 1,
    name: "Jendela Jatim",
    description:
      "A website showcasing several famous tourist destinations in East Java, Indonesia",
    longDesc: "",
    image: "/projects/jendela-jatim.png",
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    role: "Frontend",
    year: "Oct 2024",
    link: "https://d4yezz.github.io/Jendela-Jatim/d4yezz.github.io/Jendela-Jatim/",
  },
  {
    id: 2,
    name: "BankSampah K8",
    description:
      "A website to help manage waste data at SMKN 8 Malang vocational school while providing economic benefits.",
    longDesc: "",
    image: "/projects/bank-sampah.png",
    tags: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    role: "Frontend",
    year: "Nov 2024",
    link: "https://d4yezz.github.io/BankSampah-K8-24/",
  },
  {
    id: 3,
    name: "Explore Ngalam",
    description:
      "A website to discover the natural beauty and diversity of tourism in Malang, East Java, Indonesia.",
    longDesc: "",
    image: "/projects/explore-ngalam.png",
    tags: ["ReactJS", "TailwindCSS", "ShadCN", "JavaScript", "Supabase"],
    role: "Fullstack",
    year: "Oct 2025",
    link: "https://explore-ngalam.vercel.app/",
  },
  {
    id: 4,
    name: "Go Rent",
    description:
      "The website provides the best car rental services with the latest cars and guaranteed professional comfort.",
    longDesc: "",
    image: "/projects/go-rent.png",
    tags: [
      "NextJS",
      "TailwindCSS",
      "JavaScript",
      "ShadCN",
      "Framer Motion",
      "Supabase",
    ],
    role: "Fullstack",
    year: "Nov 2025",
    link: "https://go-rent-wine.vercel.app/",
  },
  {
    id: 5,
    name: "Pentol Ngetop",
    description:
      "Trusted Spicy Meatball Ordering Website. With an admin dashboard system to manage orders from buyers.",
    longDesc: "",
    image: "/projects/pentol-ngetop.png",
    tags: [
      "NextJS",
      "TailwindCSS",
      "JavaScript",
      "ShadCN",
      "Framer Motion",
      "Supabase",
    ],
    role: "Fullstack",
    year: "Dec 2025",
    link: "https://pentol-ngetop.vercel.app/",
  },
  {
    id: 6,
    name: "Dayezzz.",
    description:
      "My portfolio website. lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    longDesc: "My portfolio website",
    image: "/helm.jpg",
    tags: [
      "NextJS",
      "TailwindCSS",
      "TypeScript",
      "Zustand",
      "Aceternity",
      "Framer Motion",
      "Lenis",
    ],
    role: "Fullstack",
    year: "Jan 2026",
    link: "https://dayezzz.vercel.app/",
  },
];
