export const techStack = [
  { name: "JavaScript", category: "Language", url: "javascript.png" },
  { name: "TypeScript", category: "Language", url: "typescript.png" },
  { name: "React", category: "Frontend Library", url: "react.png" },
  { name: "Next.js", category: "React Framework", url: "nextjs.png" },
  { name: "Tailwind CSS", category: "Styling", url: "tailwind.png" },
  { name: "shadcn/ui", category: "UI Components", url: "shadcn.png" },
  { name: "Framer Motion", category: "Animation", url: "motion.png" },
  { name: "Lenis", category: "Scroll & UX", url: "lenis.png" },
  { name: "Zustand", category: "State Management", url: "zustand.png" },
  { name: "TanStack Query", category: "Data Fetching", url: "tanstack.png" },
  {
    name: "Express.js",
    category: "Backend Framework",
    url: "express.svg",
  },
  { name: "Supabase", category: "Backend / BaaS", url: "supabase.jpeg" },
  { name: "Prisma", category: "Database ORM", url: "prisma.png" },
  { name: "MySQL", category: "Database", url: "mysql.png" },
  { name: "PostgreSQL", category: "Database", url: "postgresql.png" },
  { name: "Playwright", category: "Testing", url: "playwright.png" },
  { name: "Git", category: "Version Control", url: "git.png" },
  { name: "Postman", category: "API Testing", url: "postman.png" },
  {
    name: "Notion",
    category: "Productivity",
    url: "notion.png",
  },
];
